### ISSUE TITLE
Discussion thread: Junctions management overhaul

### ISSUE THREAD

**Issue by kianzarrin** [kianzarrin/myrepo#5]
This is a discussion threat for #2 #3 #4. Since these are all junction operations there may be a need for a new mod called Junction Skins or Junction Manager or something. Or should I just merge this with TMPE/Network skins.
 TMPE does not deal with textures. 
Network skins deals with segments not junctions or segment ends.

**Comment by originalfoo** [comment]
Test it in little mods maybe, but ultimately it will evolve to something that the pathfinder (and AIs?) needs to know about IMO. There's a whole boat load of stuff that can be done to junctions.

For example: [Virtual Junctions](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/14) - various crazy pedestrian crossings, bike waiting areas at traffic lights, traffic lights dedicated to pedestrian crossings, etc.

Then we get to stuff like [lane customisation](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/515) - not so much about junctions management, but closely related I think. So you posted this image in one of the issues linked in OP:

![image](https://user-images.githubusercontent.com/1386719/70648367-d4184100-1c42-11ea-830d-a90e5e716af8.png)

We could make the superfluous lanes 'striped' and not accessible to vehicles, for example. Or turn them in to parking lanes or some other crazy stuff.

**Comment by kianzarrin** [comment]
This could also be part of the junction manager:
https://youtu.be/45zxp8yeSwg?t=338
